### ISSUE TITLE
1.19.2 Crash on World Load

### ISSUE THREAD

**Issue by Gamerbolts** [Domaman202/Trap-Expansion#1]
Hello! I put your mod into my modpack and right before it loaded into the world I crashed. Here is the crash log

https://pastebin.com/5FT3hG25

Any help is appreciated. Thank you!

**Comment by Domaman202** [comment]
https://www.curseforge.com/minecraft/mc-mods/iron-burn-fix-fabric/files/4041730

**Comment by Domaman202** [comment]
I apologize for the delay in handling complaints.

**Comment by Domaman202** [comment]
https://www.curseforge.com/minecraft/mc-mods/trap-expansion-fabric-remake/files/4041736
